
function ObjectList = Objects
    ObjectList(1) = struct(...
        'Name', 'SquareGrid',...
        'Type', 'Line',...
        'Vertices', [...
            [ -1, -1 ]',...
            [  0, -1 ]',...
            [  1, -1 ]',...
            [ -1,  0 ]',...
            [  1,  0 ]',...
            [ -1,  1 ]',...
            [  0,  1 ]',...
            [  1,  1 ]'...
        ],...
        'Indices', [...
            1, 3,...
            4, 5,...
            6, 8,...
            1, 6,...
            2, 7,...
            3, 8 ...
        ]...
    );
    ObjectList(2) = struct(...
        'Name', 'FilledSquare',...
        'Type', 'TriangleStrip',...
        'Vertices', [...
            [  0,  0 ]',...
            [  1,  0 ]',...
            [  0, -1 ]',...
            [  1, -1 ]'...
        ],...
        'Indices', [...
            1, 3, 2, 4 ...
        ]...
    );

    function drawObject(Object)
        if ~isstruct(Object) && ~isfield(Object, 'Vertices')
            disp('[ERR] Cannot draw non-struct');
        end
        disp('Foo')

        switch(Object.Type)
            case 'Line'
            case 'Area'
        end
    end
end
