
function Window = setupUI(Settings)
    % get the screen dimensions
    ScreenSize = get(0, 'ScreenSize');
    Settings.ScreenSize = ScreenSize(3:4);

    Window.Figure = figure(...
          'Visible', 'off' ...
        , 'Position', [ (Settings.ScreenSize - Settings.Dimension) / 2, Settings.Dimension ] ...
        , 'SizeChangedFcn', @onResize ...
        ... % TODO : add key handling
        ... % , 'WindowKeyPressFcn', @keyPressed ...
    );

    % plot panel
    Window.PlotPanel = uipanel(Window.Figure,...
          'Title', 'Plot' ...
        , 'FontSize', 12 ...
    );
    Window.PlotPanel.Units = 'pixels';

    Window.Axes = axes(...
          'Parent', Window.PlotPanel ...
        , 'Units', 'pixels' ...
    );

    % list panel
    Window.ListPanel = uipanel(Window.Figure,...
          'Title', 'Transformations' ...
        , 'FontSize', 12 ...
    );
    Window.ListPanel.Units = 'pixels';

    Window.TransformationList = uicontrol(Window.ListPanel,...
        'Style', 'listbox' ...
        , 'String', {} ...
        , 'FontSize', 14 ...
        , 'Callback', @onSelect ...
    );
    Window.SelectedIndex = Window.TransformationList.Value;

    ArrowSymbols = struct(...
          'up', sprintf('\x2191') ...
        , 'down', sprintf('\x2193') ...
        , 'left', sprintf('\x2190') ...
        , 'right', sprintf('\x2192') ...
        , 'top', sprintf('\x219f') ...
        , 'bottom', sprintf('\x21a1') ...
        , 'first', sprintf('\x219e') ...
        , 'last', sprintf('\x21a0') ...
    );
    Window.TransformationButtonTop = uicontrol(Window.ListPanel,...
          'Style', 'pushbutton' ...
        , 'String', ArrowSymbols.top ...
        , 'FontSize', 30 ...
        , 'Callback', @(Source, Event) listSwap('first') ...
        , 'Enable', 'off' ...
    );
    Window.TransformationButtonUp = uicontrol(Window.ListPanel,...
          'Style', 'pushbutton' ...
        , 'String', ArrowSymbols.up ...
        , 'FontSize', 30 ...
        , 'Callback', @(Source, Event) listSwap('prev') ...
        , 'Enable', 'off' ...
    );
    Window.TransformationButtonDown = uicontrol(Window.ListPanel,...
          'Style', 'pushbutton' ...
        , 'String', ArrowSymbols.down ...
        , 'FontSize', 30 ...
        , 'Callback', @(Source, Event) listSwap('next') ...
        , 'Enable', 'off' ...
    );
    Window.TransformationButtonBottom = uicontrol(Window.ListPanel,...
          'Style', 'pushbutton' ...
        , 'String', ArrowSymbols.bottom ...
        , 'FontSize', 30 ...
        , 'Callback', @(Source, Event) listSwap('last') ...
        , 'Enable', 'off' ...
    );
    Window.TransformationButtonAdd = uicontrol(Window.ListPanel,...
          'Style', 'pushbutton' ...
        , 'String', 'Add transformation' ...
        , 'FontSize', 12 ...
        , 'Callback', @addTransformation ...
    );
    Window.TransformationButtonRemove = uicontrol(Window.ListPanel,...
          'Style', 'pushbutton' ...
        , 'String', 'Remove transformation' ...
        , 'FontSize', 12 ...
        , 'Callback', @removeTransformation ...
        , 'Enable', 'off' ...
    );

    % control panel
    Window.ControlPanel = uipanel(Window.Figure,...
          'Title', 'Controls' ...
        , 'FontSize', 12 ...
    );
    Window.ControlPanel.Units = 'pixels';

    Window.TransformationTabs = uitabgroup(Window.ControlPanel ...
      , 'Units', 'pixels' ...
    );
	
	Window.TransformationTabs.SelectionChangedFcn = @setTransformation;
	
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Translation
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    Window.TranslationTab = uitab(Window.TransformationTabs ...
      , 'Title', 'Translation' ...
    );    
    Window.TranslationInputChange = uicontrol(Window.TranslationTab,...
          'Style', 'edit' ...
        , 'Position', [110 110 50 50] ...
        , 'FontSize', 10 ...
        , 'String', 1.0 ...
    );
    Window.TranslationButtonMinusX = uicontrol(Window.TranslationTab,...
          'Style', 'pushbutton' ...
        , 'String', '-X' ...
        , 'Position', [60 110 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeTranslation('-','X') ...
    );
    Window.TranslationButtonPlusX = uicontrol(Window.TranslationTab,...
          'Style', 'pushbutton' ...
        , 'String', '+X' ...
        , 'Position', [160 110 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeTranslation('+','X') ...
    );
    Window.TranslationInputX = uicontrol(Window.TranslationTab,...
          'Style', 'edit' ...
        , 'Position', [210 110 50 50] ...
        , 'FontSize', 10 ...
        , 'Callback', @(Source, Event) setTranslation('X') ...
        , 'String', 0.0 ...
    );
    Window.TranslationButtonPlusY = uicontrol(Window.TranslationTab,...
          'Style', 'pushbutton' ...
        , 'String', '+Y' ...
        , 'Position', [110 160 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeTranslation('+','Y') ...
    );
    Window.TranslationButtonMinusY = uicontrol(Window.TranslationTab,...
          'Style', 'pushbutton' ...
        , 'String', '-Y' ...
        , 'Position', [110 60 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeTranslation('-','Y') ...
    );
    Window.TranslationInputY = uicontrol(Window.TranslationTab,...
          'Style', 'edit' ...
        , 'Position', [110 210 50 50] ...
        , 'FontSize', 10 ...
        , 'Callback', @(Source, Event) setTranslation('Y') ...
        , 'String', 0.0 ...
    );
    Window.TranslationButtonMinusZ = uicontrol(Window.TranslationTab,...
          'Style', 'pushbutton' ...
        , 'String', '-Z' ...
        , 'Position', [60 60 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeTranslation('-','Z') ...
    );
    Window.TranslationButtonPlusZ = uicontrol(Window.TranslationTab,...
          'Style', 'pushbutton' ...
        , 'String', '+Z' ...
        , 'Position', [160 160 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeTranslation('+','Z') ...
    );
    Window.TranslationInputZ = uicontrol(Window.TranslationTab,...
          'Style', 'edit' ...
        , 'Position', [210 210 50 50] ...
        , 'FontSize', 10 ...
        , 'Callback', @(Source, Event) setTranslation('Z') ...
        , 'String', 0.0 ...
    );
    
    
    function changeTranslation(Sign, Value)
        switch(Value)
            case 'X'
                x = str2double(Window.TranslationInputX.String);
            case 'Y'
                x = str2double(Window.TranslationInputY.String);
            case 'Z'
                x = str2double(Window.TranslationInputZ.String);
        end
        if (isempty(x))
            x = 0;
        end
        
        change = str2double(Window.TranslationInputChange.String);
        
        if (isempty(change))
            change = 0;
        end
        
        switch(Sign)
            case '-'
                x = x-change;
            case '+'
                x = x+change;
        end
        
        switch(Value)
            case 'X'
                Window.TranslationInputX.String = x;
            case 'Y'
                Window.TranslationInputY.String = x;
            case 'Z'
                Window.TranslationInputZ.String = x;
        end
        setTranslation(Value);
        
    end

    function setTranslation(Value)
        switch(Value)
            case 'X'
                x = str2double(Window.TranslationInputX.String)
            case 'Y'
                x = str2double(Window.TranslationInputY.String)
            case 'Z'
                x = str2double(Window.TranslationInputZ.String)
        end
        
        Length = length(Window.TransformationList.String);
        if Length >= 1
            
            switch(Value)
                case 'X'
                    Window.Transformations{Window.SelectedIndex}.X = x;
                case 'Y'
                    Window.Transformations{Window.SelectedIndex}.Y = x;
                case 'Z'
                    Window.Transformations{Window.SelectedIndex}.Z = x;
            end
            Window.TransformationList.String(Window.SelectedIndex) = { getTransformationString(Window.Transformations{Window.SelectedIndex})};
        end

        onPlot;
    end

%{
    Window.TranslationMag = uicontrol(Window.TranslationTab ...
      , 'Style', 'edit' ...
    );
%}
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Scaling
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    Window.ScalingTab = uitab(Window.TransformationTabs ...
      , 'Title', 'Scaling' ...
    );
    Window.ScalingInputChange = uicontrol(Window.ScalingTab,...
          'Style', 'edit' ...
        , 'Position', [110 110 50 50] ...
        , 'FontSize', 10 ...
        , 'String', 1.0 ...
    );
    Window.ScalingButtonMinusX = uicontrol(Window.ScalingTab,...
          'Style', 'pushbutton' ...
        , 'String', '-X' ...
        , 'Position', [60 110 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeScaling('-','X') ...
    );
    Window.ScalingButtonPlusX = uicontrol(Window.ScalingTab,...
          'Style', 'pushbutton' ...
        , 'String', '+X' ...
        , 'Position', [160 110 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeScaling('+','X') ...
    );
    Window.ScalingInputX = uicontrol(Window.ScalingTab,...
          'Style', 'edit' ...
        , 'Position', [210 110 50 50] ...
        , 'FontSize', 10 ...
        , 'Callback', @(Source, Event) setScaling('X') ...
        , 'String', 0.0 ...
    );
    Window.ScalingButtonPlusY = uicontrol(Window.ScalingTab,...
          'Style', 'pushbutton' ...
        , 'String', '+Y' ...
        , 'Position', [110 160 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeScaling('+','Y') ...
    );
    Window.ScalingButtonMinusY = uicontrol(Window.ScalingTab,...
          'Style', 'pushbutton' ...
        , 'String', '-Y' ...
        , 'Position', [110 60 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeScaling('-','Y') ...
    );
    Window.ScalingInputY = uicontrol(Window.ScalingTab,...
          'Style', 'edit' ...
        , 'Position', [110 210 50 50] ...
        , 'FontSize', 10 ...
        , 'Callback', @(Source, Event) setScaling('Y') ...
        , 'String', 0.0 ...
    );
    Window.ScalingButtonMinusZ = uicontrol(Window.ScalingTab,...
          'Style', 'pushbutton' ...
        , 'String', '-Z' ...
        , 'Position', [60 60 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeScaling('-','Z') ...
    );
    Window.ScalingButtonPlusZ = uicontrol(Window.ScalingTab,...
          'Style', 'pushbutton' ...
        , 'String', '+Z' ...
        , 'Position', [160 160 50 50] ...
        , 'FontSize', 20 ...
        , 'Callback', @(Source, Event) changeScaling('+','Z') ...
    );
    Window.ScalingInputZ = uicontrol(Window.ScalingTab,...
          'Style', 'edit' ...
        , 'Position', [210 210 50 50] ...
        , 'FontSize', 10 ...
        , 'Callback', @(Source, Event) setScaling('Z') ...
        , 'String', 0.0 ...
    );

    function changeScaling(Sign, Value)
        switch(Value)
            case 'X'
                x = str2double(Window.ScalingInputX.String);
            case 'Y'
                x = str2double(Window.ScalingInputY.String);
            case 'Z'
                x = str2double(Window.ScalingInputZ.String);
        end
        if (isempty(x))
            x = 0;
        end
        
        change = str2double(Window.ScalingInputChange.String);
        
        if (isempty(change))
            change = 0;
        end
        
        switch(Sign)
            case '-'
                x = x-change;
            case '+'
                x = x+change;
        end
        
        switch(Value)
            case 'X'
                Window.ScalingInputX.String = x;
            case 'Y'
                Window.ScalingInputY.String = x;
            case 'Z'
                Window.ScalingInputZ.String = x;
        end
        setScaling(Value);
        
    end

    function setScaling(Value)
        switch(Value)
            case 'X'
                x = str2double(Window.ScalingInputX.String)
            case 'Y'
                x = str2double(Window.ScalingInputY.String)
            case 'Z'
                x = str2double(Window.ScalingInputZ.String)
        end
        
        Length = length(Window.TransformationList.String);
        if Length >= 1
            
            switch(Value)
                case 'X'
                    Window.Transformations{Window.SelectedIndex}.X = x;
                case 'Y'
                    Window.Transformations{Window.SelectedIndex}.Y = x;
                case 'Z'
                    Window.Transformations{Window.SelectedIndex}.Z = x;
            end
            Window.TransformationList.String(Window.SelectedIndex) = { getTransformationString(Window.Transformations{Window.SelectedIndex})};
        end

        onPlot;
    end

    Window.TranslationPanel = uipanel(Window.ControlPanel ...
      , 'BorderWidth', 0 ...
      , 'BackgroundColor', [ 1, 0, 0 ] ...
    );
    Window.TranslationPanel.Units = 'pixels';
    Window.TranslationPanel.Visible = 'off';

    Window.SelectListeners = {};
    Window.Transformations = {};


    Window.setVisible = @setVisible;
    Window.addSelectListener = @(Listener) addListener(Listener);

    Window.addSelectListener(@onTransformationChange);

    function onTransformationChange(Index)
    end

    function addListener(Listener)
        NumListeners = length(Window.SelectListeners);
        Window.SelectListeners{NumListeners + 1} = Listener;
    end
	
	function setTransformation(src, eventdata)
        Transformation = lower(eventdata.NewValue.Title);
        Length = length(Window.TransformationList.String);
        if Length >= 1
            switch(Transformation)
                case 'translation'
                    Window.Transformations{Window.SelectedIndex}.X = 0;
                    Window.Transformations{Window.SelectedIndex}.Y = 0;
                case 'scaling'
                    Window.Transformations{Window.SelectedIndex}.X = 1;
                    Window.Transformations{Window.SelectedIndex}.Y = 1;
                case 'rotation'
                    Window.Transformations{Window.SelectedIndex}.Rx = 0;
                    Window.Transformations{Window.SelectedIndex}.Ry = 0;
            end
            Window.Transformations{Window.SelectedIndex}.Type = Transformation;
            Window.TransformationList.String(Window.SelectedIndex) = { getTransformationString(Window.Transformations{Window.SelectedIndex})};
        end

        onPlot;
    end

    function listSwap(Index)
        switch(Index)
            case 'first'
                To = 1;
            case 'prev'
                To = Window.SelectedIndex - 1;
            case 'next'
                To = Window.SelectedIndex + 1;
            case 'last'
                To = length(Window.TransformationList.String);
        end

        Temp = Window.Transformations{Window.SelectedIndex};
        Window.Transformations{Window.SelectedIndex} = Window.Transformations{To};
        Window.Transformations{To} = Temp;

        swap(Window.SelectedIndex, To);
        onPlot;

        function swap(From, To)
            ListLength = length(Window.TransformationList.String);
            if 1 <= From && From <= ListLength && 1 <= To && To <= ListLength && From ~= To
                Iter = sign(To - From);
                while abs(From - To) > 0
                    Next = From + Iter;
                    Tmp = Window.TransformationList.String(Next);
                    Window.TransformationList.String(Next) = Window.TransformationList.String(From);
                    Window.TransformationList.String(From) = Tmp;
                    From = Next;
                end
                Window.SelectedIndex = To;
                Window.TransformationList.Value = Window.SelectedIndex;
            end
        end
    end

    Value = 1;
    function addTransformation(Source, Event)
        LastIndex = length(Window.TransformationList.String);
        if rand() < 0.5
            Window.Transformations{LastIndex + 1} = struct(...
                  'Type', 'translation' ...
                , 'X', (floor(rand() * 8) - 4) / 2  ...
                , 'Y', (floor(rand() * 8) - 4) / 2 ...
            );
        else
            Window.Transformations{LastIndex + 1} = struct(...
                'Type', 'rotation' ...
              , 'Rx', pi * (floor(rand() * 16) - 8) / 4 ...
              , 'Ry', 0 * pi * (floor(rand() * 16) - 8) / 4 ...
              , 'Rz', 0 * pi * (floor(rand() * 16) - 8) / 4 ...
            );
        end

        Window.TransformationList.String(LastIndex + 1) = { getTransformationString(Window.Transformations{LastIndex + 1}) };
        Value = Value + 1;
        Window.SelectedIndex = LastIndex + 1;
        Window.TransformationList.Value = Window.SelectedIndex;

        Window.TransformationButtonRemove.Enable = 'on';
        Window.TransformationButtonUp.Enable = 'on';
        Window.TransformationButtonDown.Enable = 'on';
        Window.TransformationButtonTop.Enable = 'on';
        Window.TransformationButtonBottom.Enable = 'on';

        onPlot;
    end

    function onPlot()
        ObjectList = Objects;
        Scale = 5;
        cla(Window.Axes);
        grid on;

        axis([ -Scale, Scale, -Scale, Scale, -Scale, Scale ]);
        set(Window.Axes, 'xtick', -1000:1000);
        set(Window.Axes, 'ytick', -1000:1000);
        set(Window.Axes, 'ztick', -1000:1000);
        xlabel('Z');
        ylabel('X');
        zlabel('Y');
        h = rotate3d;
        h.Enable = 'on';

        hold on;

        % plot main axes
        plot3([ -1000, 1000 ], [ 0, 0 ], [ 0, 0 ], 'r' ...
           , [ 0, 0 ], [ -1000, 1000 ], [ 0, 0 ], 'b' ...
           , [ 0, 0 ], [ 0, 0 ], [ -1000, 1000 ], 'g');

        for I = 1:length(ObjectList)
            plotObject(ObjectList(I));
        end

        for I = 1:length(ObjectList)
            plotObjectTransformed(ObjectList(I), Window.Transformations);
        end

        hold off;
    end

    function removeTransformation(Source, Event)
        Length = length(Window.TransformationList.String);
        if Length >= 1
            Window.Transformations(Window.SelectedIndex) = [];
            Window.TransformationList.String(Window.SelectedIndex) = [];
            Window.SelectedIndex = min(max(0, Window.SelectedIndex), Length - 1);
            Window.TransformationList.Value = Window.SelectedIndex;

            if Length == 1
                Source.Enable = 'off';
                Window.TransformationButtonUp.Enable = 'off';
                Window.TransformationButtonDown.Enable = 'off';
                Window.TransformationButtonTop.Enable = 'off';
                Window.TransformationButtonBottom.Enable = 'off';
            end
        end

        onPlot;
    end

    function Description = getTransformationString(Transformation)
        switch(Transformation.Type)
            case 'translation'
                Description = sprintf('Translation(%g, %g)', Transformation.X, Transformation.Y);
			case 'scaling'
                Description = sprintf('Scaling(%g, %g)', Transformation.X, Transformation.Y);
            case 'rotation'
                Description = sprintf('Rotation(%g\x03C0, %g\x03C0, %g\x03C0)', Transformation.Rx / pi, Transformation.Ry / pi, Transformation.Rz / pi);
            otherwise
                Description = 'unknown transformation';
        end
    end

    function onSelect(Source, Event)
        Window.SelectedIndex = Source.Value;
        NumListeners = length(Window.SelectListeners);
        for I = 1:NumListeners
            Window.SelectListeners{I}(Window.SelectedIndex);
        end
    end

    function setVisible(Visible)
        if Visible
            onPlot;
            Window.Figure.Visible = 'on';
        else
            Window.Figure.Visible = 'off';
        end
    end

    function onResize(Source, Event)
        % enforce minimum position
        Temp = Source.Position(1:2);
        Source.Position(3) = max(Source.Position(3), Settings.MinDimension(1));
        Source.Position(4) = max(Source.Position(4), Settings.MinDimension(2));
        Source.Position(1) = Temp(1);
        Source.Position(2) = Temp(2);

        MaxVerticalPadding = max(Settings.Padding.Top, Settings.Padding.Bottom);
        MaxHorizontalPadding = max(Settings.Padding.Left, Settings.Padding.Right);
        Settings.Dimension = Source.Position(3:4);
        PlotPanelDimension = [...
            (Settings.Dimension(1) - (Settings.Padding.Left + Settings.Padding.Right + MaxHorizontalPadding)) / 2,...
            Settings.Dimension(2) - (Settings.Padding.Top + Settings.Padding.Bottom) ...
        ];
        Window.PlotPanel.Position = [ Settings.Padding.Left, Settings.Padding.Bottom, PlotPanelDimension ];
        ControlPanelsDimension = [...
            PlotPanelDimension(1),...
            (Settings.Dimension(2) - (Settings.Padding.Top + Settings.Padding.Bottom + MaxVerticalPadding)) / 2,...
        ];
        Window.ListPanel.Position = [...
            Settings.Padding.Left + MaxHorizontalPadding + PlotPanelDimension(1),...
            Settings.Padding.Bottom + MaxVerticalPadding + ControlPanelsDimension(2),...
            ControlPanelsDimension ];
        Window.ControlPanel.Position = [...
            Settings.Padding.Left + MaxHorizontalPadding + PlotPanelDimension(1),...
            Settings.Padding.Bottom,...
            ControlPanelsDimension ];
        TransformationListHeight = ControlPanelsDimension(2) - 30 - (Settings.Padding.Top + Settings.Padding.Bottom);
        Window.TransformationList.Position = [ Settings.Padding.Left, Settings.Padding.Bottom + MaxVerticalPadding + 30,...
            ControlPanelsDimension(1) - Settings.Padding.Left - (50 + MaxHorizontalPadding * 2),...
            TransformationListHeight - MaxVerticalPadding - 30 ...
        ];

        TransformationListCenter = TransformationListHeight / 2 + Settings.Padding.Bottom;
        Window.TransformationButtonTop.Position = [...
            Window.TransformationList.Position(1) + Window.TransformationList.Position(3) + MaxHorizontalPadding,...
            TransformationListCenter + ((3 / 2) * MaxVerticalPadding) + 60,...
            50,...
            60];
        Window.TransformationButtonUp.Position = [...
            Window.TransformationList.Position(1) + Window.TransformationList.Position(3) + MaxHorizontalPadding,...
            TransformationListCenter + (MaxVerticalPadding / 2),...
            50,...
            60];
        Window.TransformationButtonDown.Position = [...
            Window.TransformationList.Position(1) + Window.TransformationList.Position(3) + MaxHorizontalPadding,...
            TransformationListCenter - 60 - (MaxVerticalPadding / 2),...
            50,...
            60];
        Window.TransformationButtonBottom.Position = [...
            Window.TransformationList.Position(1) + Window.TransformationList.Position(3) + MaxHorizontalPadding,...
            TransformationListCenter - (2 * 60) - ((3 / 2) * MaxVerticalPadding),...
            50,...
            60];
        ButtonWidth = Window.TransformationList.Position(3) / 2 - (Settings.Padding.Left + Settings.Padding.Right);
        Window.TransformationButtonAdd.Position = [...
            Window.TransformationList.Position(1) + Settings.Padding.Left,...
            Settings.Padding.Bottom,...
            ButtonWidth,...
            30 ...
        ];
        Window.TransformationButtonRemove.Position = [...
            Window.TransformationList.Position(1) + Settings.Padding.Left + MaxHorizontalPadding + ButtonWidth,...
            Settings.Padding.Bottom,...
            ButtonWidth,...
            30 ...
        ];

        Window.ControlPanel.Position = [ ...
          , Settings.Padding.Left + MaxHorizontalPadding + PlotPanelDimension(1) ...
          , Settings.Padding.Bottom ...
          , ControlPanelsDimension ...
        ];
        Window.TransformationTabs.Position = [ ...
          , Settings.Padding.Left ...
          , Settings.Padding.Bottom ...
          , ControlPanelsDimension - [ Settings.Padding.Left + Settings.Padding.Right, Settings.Padding.Top + Settings.Padding.Bottom + 30 ] ...
        ];
        Window.TranslationLabelX.Position = [ ...
          , Settings.Padding.Left ...
          , Window.TransformationTabs.Position(3) - 400 ...
          , 180 ...
          , 30 ...
        ];

        AxesSize = min(Window.PlotPanel.Position(3:4));
        VerticalLeft = Window.PlotPanel.Position(4) - AxesSize;
        Window.Axes.Position = [ 55, 55 + VerticalLeft, [ AxesSize, AxesSize ] - 110 ];
    end
end
